Repository suno0140/FE-CloneCode, pull requests merged in 2022-12, with the labels that each got.

#3 Global 스타일 지정, Header, Footer 제작
  src/App.js
  src/component/common/FlexContainer.jsx
  src/layout/Footer.jsx
  src/layout/Header.jsx
  src/layout/Layout.jsx
  src/layout/header/Header.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/ScreenHeader.jsx
  src/pages/Main.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
  src/style/theme.js
Labels: fix, design

#4 feat: design Login
  src/component/login/Screen.jsx
  src/pages/Login.jsx
  src/shared/Router.jsx
  src/utils/img/s62_login_login_icon.jpg
Labels: design

#5 design : 헤더 및 푸터 레이아웃 수정
  src/component/common/FlexContainer.jsx
  src/layout/Footer.jsx
  src/layout/Layout.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/ScreenHeader.jsx
Labels: design

#6 Fix : 명칭 수정
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainCarousel/screen/MainCarouselScreen.jsx
  src/component/main/mainItemList/screen/MainItemListScreen.jsx
  src/component/productlist/productListGrid/screen/ProductListGridScreen.jsx
  src/component/productlist/productlistLayout/components/ClickBox.jsx
  src/component/productlist/productlistLayout/components/ProductListFooter.jsx
  src/component/productlist/productlistLayout/components/ProductListHeader.jsx
  src/component/productlist/productlistLayout/components/SubCategory.jsx
  src/layout/Footer.jsx
  src/layout/Layout.jsx
  src/layout/header/Header.jsx
  src/layout/header/screen/HeaderScreen.jsx
  src/pages/Main.jsx
  src/pages/ProductList.jsx
  src/shared/GlobalStyle.jsx
  src/shared/Router.jsx
Labels: fix, design

#8 Feat/#2
  src/component/login/Screen.jsx
  src/component/signup/Screen.jsx
  src/pages/Signup.jsx
  src/shared/Router.jsx
  src/utils/img/s62_login_login_icon.jpg
Labels: design

#9 design: 로그인,회원가입page 완성
  src/component/login/Screen.jsx
  src/component/signup/Screen.jsx
Labels: design

#10 feat : product layout 제작
  src/component/product/productCoreInfo/components/ProductCoreInfoTextBox.jsx
  src/component/product/productCoreInfo/screen/ProductCoreInfoScreen.jsx
  src/component/product/productInfo/components/ClickBox.jsx
  src/component/product/productInfo/components/CommentItem.jsx
  src/component/product/productInfo/components/CommentList.jsx
  src/component/product/productInfo/components/ProductInfoImg.jsx
  src/component/product/productInfo/screen/ProductInfoScreen.jsx
  src/component/product/productInfoButtonList/screen/ProductInfoButtonList.jsx
  src/pages/Product.jsx
  src/shared/Router.jsx
Labels: design

#11 rename: login,signup file 분리
  src/component/login/Components.jsx
  src/component/login/Contants.jsx
  src/component/login/LoginScreen.jsx
  src/component/login/Screen.jsx
  src/component/login/logininput/idinput/IdinputScreen.jsx
  src/component/login/logininput/loginbtn/LoginBtn.jsx
  src/component/login/logininput/passwordinput/PasswordInputScreen.jsx
  src/component/login/sociallogin/SocialScreen.jsx
  src/component/signup/Screen.jsx
  src/component/signup/SignupScreen.jsx
  src/component/signup/signupinputbox/SignupInputScreen.jsx
  src/component/signup/signupinputbox/emailinput/Screen.jsx
  src/component/signup/signupinputbox/idinput/Screen.jsx
  src/component/signup/signupinputbox/nameinput/Screen.jsx
  src/component/signup/signupinputbox/passwordinput/Screen.jsx
  src/component/signup/signupinputbox/signupbtn/SignupBtnScreen.jsx
  src/component/signup/sociallogin/SocialScreen.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
Labels: rename

#16 feat : api 관련 url 추가
  src/core/api.jsx
  src/core/index.jsx
Labels: feat

#17 fix : api 관련 수정 및 config store 기본 틀 구현
  package.json
  src/core/api.jsx
  src/core/index.jsx
  src/index.js
  src/redux/config/configstore.jsx
Labels: fix

#18 Feat : 메인 페이지, 상세 리스트 페이지 디자인 구현, 서버 연결
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainCarousel/components/Carousel.jsx
  src/component/main/mainItemList/components/GetNewItems.jsx
  src/component/main/mainItemList/screen/MainItemListScreen.jsx
  src/component/productlist/productListGrid/components/GetProduct.jsx
  src/component/productlist/productListGrid/screen/ProductListGridScreen.jsx
  src/core/index.jsx
  src/hooks/useScrollPosition.jsx
  src/layout/Layout.jsx
  src/layout/header/components/HoverBox.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/HeaderScreen.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/mainNewItemSlice.js
  src/redux/modules/productListSlice.js
  src/styles/animations.js
Labels: feat

#19 Feature/#15
  package-lock.json
  src/component/cart/cartmiddle/CartMiddleScreen.jsx
  src/component/cart/carttablebottom/CartTableBottom.jsx
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
  src/component/cart/carttabletop/CartFootTable.jsx
  src/component/cart/carttabletop/CartHeadTable.jsx
  src/component/cart/screen/CartScreen.jsx
  src/component/login/Hooks.jsx
  src/component/login/logininput/idinput/IdinputScreen.jsx
  src/component/login/logininput/loginbtn/LoginBtn.jsx
  src/component/login/logininput/passwordinput/PasswordInputScreen.jsx
  src/component/login/screen/LoginScreen.jsx
  src/component/signup/screen/SignupScreen.jsx
  src/component/signup/signupinputbox/SignupInputScreen.jsx
  src/component/signup/signupinputbox/emailinput/Screen.jsx
  src/component/signup/signupinputbox/idinput/Hook.jsx
  src/component/signup/signupinputbox/idinput/Screen.jsx
  src/component/signup/signupinputbox/nameinput/Screen.jsx
  src/component/signup/signupinputbox/passwordinput/Screen.jsx
  src/component/signup/signupinputbox/signupbtn/SignupBtnScreen.jsx
  src/core/api.jsx
  src/pages/Cart.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/signUpSlice.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: feat

#20 feat : 메인 페이지 이미지 캐러셀 기능 추가
  src/component/main/mainCarousel/components/Carousel.jsx
  src/component/main/mainCarousel/screen/MainCarouselScreen.jsx
  src/layout/Layout.jsx
  yarn.lock
Labels: feat

#21 Fix : hover, api 이미지, footer 수정
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainItemList/components/GetNewItems.jsx
  src/component/productlist/productListGrid/components/GetProduct.jsx
  src/component/productlist/productlistLayout/components/ProductListHeader.jsx
  src/layout/Footer.jsx
  src/layout/header/components/HoverBox.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/HeaderScreen.jsx
Labels: fix

#24 Fix : 헤더 호버와 메인 버튼 작동하지 않는 문제 수정
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainCarousel/components/Carousel.jsx
  src/component/main/mainCarousel/screen/MainCarouselScreen.jsx
  src/component/productlist/productListGrid/screen/ProductListGridScreen.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/HeaderScreen.jsx
  src/redux/modules/subProduct
Labels: fix

#26 fix : 캐러셀 화살표 추가
  src/component/main/mainCarousel/components/Carousel.jsx
Labels: design

#28 docs: 코드수정
  src/component/login/logininput/IdinputScreen.jsx
  src/component/product/productInfo/components/CommentItem.jsx
  src/pages/Product.jsx
Labels: docs

#29 Feat : 메인 페이지, 상품 리스트 페이지 전반 기능 정리
  public/imgs/cart.svg
  public/imgs/search.svg
  public/index.html
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainCarousel/components/Carousel.jsx
  src/component/main/mainCarousel/screen/MainCarouselScreen.jsx
  src/component/productlist/productListGrid/components/GetProduct.jsx
  src/component/productlist/productListGrid/screen/ProductListGridScreen.jsx
  src/component/productlist/productlistLayout/components/ClickBox.jsx
  src/component/productlist/productlistLayout/components/ProductListFooter.jsx
  src/component/productlist/productlistLayout/components/ProductListHeader.jsx
  src/component/productlist/productlistLayout/components/SubCategory.jsx
  src/core/api.jsx
  src/hooks/useScrollFadeIn.jsx
  src/layout/header/components/HeaderFirst.jsx
  src/layout/header/components/HeaderSecond.jsx
  src/layout/header/components/LinkButton.jsx
  src/layout/header/screen/HeaderScreen.jsx
  src/pages/ProductList.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/headerSlice.js
  src/redux/modules/productListSlice.js
  src/redux/modules/subProduct
Labels: feat, refactor

#31 상품상세페이지 구현완료
  src/component/cart/carttablebottom/CartTableBottom.jsx
  src/component/product/productCoreInfo/components/CountButton.jsx
  src/component/product/productCoreInfo/components/ProductCoreInfoTextBox.jsx
  src/component/product/productCoreInfo/screen/ProductCoreInfoScreen.jsx
  src/component/product/productInfo/components/ClickBox.jsx
  src/component/product/productInfo/components/CommentList.jsx
  src/component/product/productInfo/components/ProductInfoImg.jsx
  src/core/api.jsx
  src/pages/Product.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/productSlice.js
  src/redux/modules/signUpSlice.js
  src/shared/Router.jsx
Labels: feat

#35 회원가입 유효성검사 오류 수정
  src/component/cart/carttablebottom/CartTableBottom.jsx
  src/component/login/logininput/IdinputScreen.jsx
  src/component/signup/signupinputbox/SignupBtnScreen.jsx
  src/component/signup/signupinputbox/SignupInputScreen.jsx
  src/component/signup/sociallogin/SocialScreen.jsx
  src/redux/modules/signUpSlice.js
Labels: fix

#37 refactor : 성능 최적화 작업
  src/component/common/FlexContainer.jsx
  src/component/common/item/ItemScreen.jsx
  src/component/main/mainCarousel/components/Carousel.jsx
  src/component/main/mainCarousel/components/CarouselArrowButton.jsx
  src/component/main/mainItemList/components/GetNewItems.jsx
  src/component/productlist/productListGrid/components/GetProduct.jsx
  src/component/productlist/productListGrid/screen/ProductListGridScreen.jsx
  src/component/productlist/productlistLayout/components/ClickBox.jsx
  src/component/productlist/productlistLayout/components/ProductListFooter.jsx
  src/component/productlist/productlistLayout/components/ProductListHeader.jsx
  src/component/productlist/productlistLayout/components/SubCategory.jsx
  src/core/api.jsx
  src/layout/Footer.jsx
  src/layout/Layout.jsx
  src/layout/header/Header.jsx
  src/layout/header/components/HeaderFirst.jsx
  src/layout/header/components/HeaderSecond.jsx
  src/layout/header/components/LinkButton.jsx
Labels: refactor

#38 feat : 토큰 키 수정
  src/component/common/item/ItemScreen.jsx
  src/component/login/sociallogin/SocialScreen.jsx
  src/component/login/sociallogin/components/SocialLoginButton.jsx
  src/component/login/sociallogin/hooks/useGithubLogin.jsx
  src/component/login/sociallogin/hooks/useKakaoLogin.jsx
  src/component/productlist/productlistLayout/components/ClickBox.jsx
  src/component/productlist/productlistLayout/components/ProductListFooter.jsx
  src/core/api.jsx
  src/core/index.jsx
  src/redux/modules/headerSlice.js
  src/redux/modules/mainNewItemSlice.js
  src/redux/modules/productListSlice.js
Labels: feat, fix

#40 feat: 장바구니 체크박스 생성
  package.json
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
  src/component/cart/screen/CartScreen.jsx
  src/component/login/logininput/IdinputScreen.jsx
  src/component/product/productCoreInfo/components/CountButton.jsx
  src/component/product/productCoreInfo/components/ProductCoreInfoTextBox.jsx
  src/pages/Cart.jsx
  src/redux/config/configstore.jsx
  src/redux/modules/cartSlice.js
  src/redux/modules/productSlice.js
  yarn.lock
Labels: feat

#41 Auto stash before merge of "main" and "origin/main"
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
Labels: feat

#43 Feat : orderlist api 연동
  src/component/login/sociallogin/hooks/useGithubLogin.jsx
  src/component/orderlist/orderlistProductList/components/OrderProductListTable.jsx
  src/component/product/productCoreInfo/components/ProductCoreInfoTextBox.jsx
  src/redux/modules/orderListSlice.js
Labels: feat, fix

#44 Feature/#36
  src/component/cart/cartmiddle/CartMiddleScreen.jsx
  src/component/cart/carttablebottom/CartTableBottom.jsx
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
  src/component/cart/carttabletop/CartFootTable.jsx
  src/component/cart/screen/CartScreen.jsx
  src/redux/modules/cartSlice.js
Labels: feat

#46 장바구니 삭제버튼 구현
  src/component/cart/carttablebottom/CartTableBottom.jsx
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
  src/component/cart/carttabletop/CartFootTable.jsx
  src/component/cart/carttabletop/CartHeadTable.jsx
  src/component/cart/screen/CartScreen.jsx
  src/redux/modules/cartSlice.js
Labels: feat

#48 fix:장바구니 수정
  src/component/cart/cartmiddle/CartMiddleScreen.jsx
  src/component/cart/carttabletop/CartBody/CartBodyTable.jsx
  src/component/cart/carttabletop/CartFootTable.jsx
  src/component/cart/screen/CartScreen.jsx
  src/component/product/productCoreInfo/components/ProductCoreInfoTextBox.jsx
  src/component/product/productInfo/screen/ProductInfoScreen.jsx
  src/component/signup/signupinputbox/SignupBtnScreen.jsx
  src/component/signup/signupinputbox/SignupInputScreen.jsx
  src/pages/Product.jsx
  src/redux/modules/cartSlice.js
Labels: fix
